language: php
sudo: false

php:
  - 5.3
  - 5.3.15
  - 5.3.16
  - 5.3.17
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - TRAVISCI=1

branches:
  only:
    - develop
    - master

notifications:
  email:
    - boris@firstbeatmedia.com

script: phpunit tests/TokenReflection
